### ISSUE TITLE
Understand the difference between this space and info.xml files

### ISSUE THREAD

**Issue by imrryr** [LearnSphere/WorkflowComponents#10]
What role does this space serve in contrast to the function of the info.xml files? Hopefully, there is not too much redundancy.... I'm not sure what I what people would want in addition to the existing detailed info.xml for the PFA and TKT components, for example. I see the posts here so far seem mostly summaries of information the info.xml files would contain...

**Comment by ctipperCMU** [comment]
Phil -- The Tetrad components/issues are a slightly different case. Typically the issues are for components that are under development or 'in design'. Peter is still working on the Tetrad components but the code was checked-in to save state when he was going to be out of the office for a few days.

So, in answer to your question, I don't see any overlap. I think the content in the Issue might well be used to write the info.xml once the component is complete.

That said, I'm making this all up as I go along as I've not used GitHub Issues before and this isn't exactly the intended use for them, I believe.

**Comment by imrryr** [comment]
OK, so it sounds like this is a space to put something like a rough draft
of the info.xml. That sounds good to me.

Phil

Philip I. Pavlik Jr.
imrryr@gmail.com
http://optimallearning.org/
