### ISSUE TITLE
Add XML and/or properties output for several analysis components

### ISSUE THREAD

**Issue by hcheng688** [LearnSphere/WorkflowComponents#28]
In order to use the OutputComparator WF component to compare the output results of various analysis components, the analysis components need to output XML and/or properties files. These components should be modified to output XML and/or properties files: RLMFitting, Linear Modeling, AFM, BKT and Python AFM.

**Comment by imrryr** [comment]
It seems PFA, TKT might also apply. Is there a document link to understand what the xml looks like available?

**Comment by hcheng688** [comment]
The outputComparator component is developed to handle generic XML/properties/tabular data. For XML,  node names can be generic as long as they are one level deep. Here is an example:
 <CATALOG>
  <CD>
    <TITLE>Empire Burlesque</TITLE>
    <ARTIST>Bob Dylan</ARTIST>
    <COUNTRY>USA</COUNTRY>
    <COMPANY>Columbia</COMPANY>
    <PRICE>10.90</PRICE>
    <YEAR>1985</YEAR>
  </CD>
  <CD>
    <TITLE>Hide your heart</TITLE>
    <ARTIST>Bonnie Tylor</ARTIST>
    <COUNTRY>UK</COUNTRY>
    <COMPANY>CBS Records</COMPANY>
    <PRICE>9.90</PRICE>
    <YEAR>1988</YEAR>
  </CD>
</CATALOG>

The outputComparator can handle well to compare outputs from the same type of component. But if we standardize the node names for common output fields, it can handle comparison across different types of analysis components. For example, we can standardize node names to what we use on Datashop Model Values export, such as:  
<ModelName>
<AIC>
<BIC>
<LogLikelihood>
<NumberOfParameters>
<NumberOfObservations>
<CrossValidationRMSE>	
<StudentStratifiedCrossValidationRMSE>
<ItemStratifiedCrossValidationRMSE>	
<UnstratifiedCrossValidationRMSE>
Of course we can add more to this list.

**Comment by hcheng688** [comment]
The outputComparator component is developed to handle generic XML/properties/tabular data. For XML, node names can be generic as long as they are one level deep. Here is an example:
`<CATALOG>`
  `<CD>`
    `<TITLE>Empire Burlesque</TITLE>`
    `<ARTIST>Bob Dylan</ARTIST>`
    `<COUNTRY>USA</COUNTRY>`
    `<COMPANY>Columbia</COMPANY>`
    `<PRICE>10.90</PRICE>`
    `<YEAR>1985</YEAR>`
  `</CD>`
  `<CD>`
    `<TITLE>Hide your heart</TITLE>`
    `<ARTIST>Bonnie Tylor</ARTIST>`
    `<COUNTRY>UK</COUNTRY>`
    `<COMPANY>CBS Records</COMPANY>`
    `<PRICE>9.90</PRICE>`
    `<YEAR>1988</YEAR>`
  `</CD>`
`</CATALOG>`
The outputComparator can handle well to compare outputs from the same type of component. But if we standardize the node names for common output fields, it can handle comparison across different types of analysis components. For example, we can standardize node names to what we use on Datashop Model Values export, such as:
`<AIC>`
`<BIC>`
`<LogLikelihood>`
`<NumberOfParameters>`
`<NumberOfObservations>`
`<CrossValidationRMSE>`
`<StudentStratifiedCrossValidationRMSE>`
`<ItemStratifiedCrossValidationRMSE>`
`<UnstratifiedCrossValidationRMSE>`
Of course we can add more to this list.

**Comment by imrryr** [comment]
Did you know my components are already outputting XML in this form? Perhaps we could begin with this output for the other components (or just overlap parts of it)?

<model_output>
  <N>1941</N>
  <Loglikelihood>-1179.29727</Loglikelihood>
  <Parameters>5</Parameters>
  <RMSE>0.44238</RMSE>
  <Accuracy>0.69603</Accuracy>
  <glmmR2fixed>0.08267</glmmR2fixed>
  <glmmR2random>0.15265</glmmR2random>
  <r2ML>0.14373</r2ML>
  <r2CU>0.19268</r2CU>
</model_output>

**Comment by hcheng688** [comment]
Added model_values and paramters XML to pythonAFM component; changed XML tag names for BKT component.
Would recommend PFA and TKT to change XML tag names: Loglikelihood, parameters and N to log_likelihood, number_of_parameters and number_of_observations.
