### ISSUE TITLE
Component to generate DataShop KC model import from OLI skill models

### ISSUE THREAD

**Issue by ctipperCMU** [LearnSphere/WorkflowComponents#36]
Norman has a "crappy skills map tools collection" that he uses to map the OLI LearningDashboard skill models ([https://drive.google.com/drive/folders/0B02uqaD3151kcUliV3BDQklRbUE]) to generate a DataShop KC model import. See what can be re-used to create a component to do this.

**Comment by pschaldenbrand** [comment]
This is now possible using the [OLI LO to KC](https://github.com/LearnSphere/WorkflowComponents/tree/dev/OliLoToKc) component.  It will convert an ods file containing the learning objects into a tab-delimited file ready for KC model imports.

Major commits: [1](https://github.com/LearnSphere/WorkflowComponents/commit/efcfdc582cd0cf46decb748252acf0e3ffb7d2ea), [2](https://github.com/LearnSphere/WorkflowComponents/commit/0392f107f4d28de7cc0302585d7770c9962847a8), and [3](https://github.com/LearnSphere/WorkflowComponents/commit/c3327b3cdc1b550046998d873ebb337326545b13)
