### ISSUE TITLE
TextConverter: update component to handle XML <-> JSON

### ISSUE THREAD

**Issue by ctipperCMU** [LearnSphere/WorkflowComponents#49]
This started as a discussion about adding support for XML-to-JSON conversion but the team has decided that we want to do more general clean-up of the component so that we can support, whenever possible, all of the various combinations -- tab-delimited, csv, xml, json -- in both directions. The thinking is we'll find a library to help with this, if we can.

**Comment by mkomisin** [comment]
Updated text converter to handle JSON <-> XML and CSV/Tab-delimited -> XML/JSON. 
We could still improve the XML/JSON -> CSV/Tab-delimited function to handle (flatten) more complex structures, but that is beyond the scope of this issue.
