### ISSUE TITLE
ComponentCreator: add Boolean as an option to the 'Option Type' dropdown

### ISSUE THREAD

**Issue by ctipperCMU** [LearnSphere/WorkflowComponents#54]
The component creator will take the user-specified type for the option and use it in the schema, e.g., FileInputHeader, xs:string. So the xs:boolean is valid; we should have "Boolean" in the drop-down for option types in the ComponentCreator component.

**Comment by pschaldenbrand** [comment]
Added ability to create components with Boolean options:
69633d532970ed68db513b326a331f51723aa588
