### ISSUE TITLE
Student Work Path Aggregation Visualization

### ISSUE THREAD

**Issue by pschaldenbrand** [LearnSphere/WorkflowComponents#56]
Create a component that can visualize the way in which students work through problems in a tutor.  There is already code that does this for an algebra tutor:
![screenshot 166](https://user-images.githubusercontent.com/14282484/49527582-3b592380-f880-11e8-881f-a121e59a83ca.png)
This proposed component would be more general than the above example though.  It could take a DataShop transaction export and visualize the paths taken by students.  Each node would be a Step.  The thickness of the link would be proportional to the number of students that took that path, and the color of the link would indicate the percent correct of the responses students gave on their way from one step to the next.

**Comment by pcarvalh** [comment]
This is very cool.  Right now it seems focused mostly on activities from tutoring systems.  Any plans to export to OLI and include page views? I'm guessing it would work with OLI activities using the Datashop transaction export, but it would be cool to have page views from the OLI activity log as well, to get a view of most common ways student work through courses.

**Comment by ctipperCMU** [comment]
Added to ComponentTypeHierarchy.xml at commit 2f3dddd.

**Comment by pschaldenbrand** [comment]
439351ae61544fe38b188c09d4e6e091e06a1a82
- Changed background
- Changed hover message on links to "[N] Student Attempts" rather than "[N] Students" since a student can work through a problem multiple times.
- Eliminated redundancies in students listed in the node hover.
