### ISSUE TITLE
Pivot: Add 'count' aggregation type.

### ISSUE THREAD

**Issue by ctipperCMU** [LearnSphere/WorkflowComponents#71]
Per email from Ken (3/2/19):

> There is a "count" aggregation (counts the number cells referenced 
> regardless of what's in the cell -- it doesn't have to be a number) in 
> Excel's PivotTable that would be very useful to have in the Tigris pivot 
> table (name?) component.    Could you add that?
> 
> I want to use it to implement a simple version of the Resource Use counter.
>

**Comment by hcheng688** [comment]
1. change aggregation method from length to count to be consistenet with excel (java wrapper and xsd files)
2. allow non-numeric columns for count function (wrapper)
