### ISSUE TITLE
Assessment Analysis component: extension of Cronbach's Alpha

### ISSUE THREAD

**Issue by pschaldenbrand** [LearnSphere/WorkflowComponents#75]
There is not currently a component to compute the average percent correct on an item in a grade book like there is in DataLab.

This issue is to propose an extension of the Cronbach's alpha where there would be additional columns for 
1. the item's percent correct
2. the standard deviation of the correctness
3. the correlation this item has with the final score.

**Comment by ctipperCMU** [comment]
Added AnalysisAssessment component; didn't delete CronbachsAlpha yet... will likely just remove from the ComponentTypeHierarchy.xml file before release.

https://github.com/LearnSphere/WorkflowComponents/commit/cbfab98794cde90ed0a092a99a71b891ff6ddb4f
