### ISSUE TITLE
File names with spaces break some components

### ISSUE THREAD

**Issue by pschaldenbrand** [LearnSphere/WorkflowComponents#93]
I was testing some components (namely Regression and Search) with a file named "DataForSpectatorSport (4).txt".  The components were in an error state upon running with the message "Tab-delimited file does not exist.".

Looking at the code, it appears that the space in the file name is breaking the way that the file name is passed to the component via the command line parameters.

The Tetrad components all have this bug.  I suspect that other java components that run externally do too and possibly components written in other languages.

**Comment by ctipperCMU** [comment]
RTT @ [https://github.com/LearnSphere/WorkflowComponents/commit/c56aa592710909b9c5bebd8d85d2b08b465f0e62](https://github.com/LearnSphere/WorkflowComponents/commit/c56aa592710909b9c5bebd8d85d2b08b465f0e62)

**Comment by ctipperCMU** [comment]
Note: I did not update the runOnWindows.bat batch files for each Tetrad component. It wasn't clear the same fix would work there and Peter is the only one using them. Sorry Peter.
