### ISSUE TITLE
OLI LO to KC component runs indefinitely if the input is not correct

### ISSUE THREAD

**Issue by pschaldenbrand** [LearnSphere/WorkflowComponents#94]
If the three tab-delimited files that are used in a zip file input to the OLI LO to KC component are not named correctly, the component seems to run indefinitely.  Instead, it should output a clear error message detailing why it is not running correctly.

The example that produced this bug was files named "[name] - problems.tsv".  The space between "-" and "problems" is incorrect.

**Comment by ctipperCMU** [comment]
RTT at [https://github.com/LearnSphere/WorkflowComponents/commit/4ee13ba58c36e049281c079cfbf0798cac3d3604]
